### ISSUE TITLE
[Bug] exercise "en/python/formattedStrings/24.md" has an issue 

### ISSUE THREAD

**Issue by vicberger** [nank1ro/codigo-questions#27] opened 2021-11-21 12:09 UTC
“Next arrow” stays greyed out after correct answer, so I cannot proceed.

**Comment by nank1ro** [comment] 2021-11-21 12:53
Hello, thank you for your report.

I was able to reproduce your bug, and it's inside the app.
I'm going to update the app tomorrow, and with the version 2.0.4 the bug should disappear.

For now you can close the exercise with the X at the top-left of the screen. Don't worry your progress will not be lost.

**Comment by nank1ro** [comment] 2021-11-21 12:53
@all-contributors please add @vicberger for bug

**Comment by nank1ro** [comment] 2021-11-22 10:05
closing because the version 2.0.4 that fixes this problem is live in both the Play Store and the App Store.
If you encounter this bug again, consider opening a new issue.

**Closed as completed by nank1ro** 2021-11-22 10:05 UTC
Labels: bug
