### ISSUE TITLE
[Bug] exercise "en/c/formattedStrings/4.md" has an issue 

### ISSUE THREAD

**Issue by ghost** [nank1ro/codigo-questions#32] opened 2021-11-22 09:07 UTC
Hi. In this question I write and try to submit my answer, but the result is never loaded. Why is that?

![7E146CF3-D490-4F66-A8E4-ABAA7BDB48EC](https://user-images.githubusercontent.com/94829947/142833247-1d810144-b7c0-4f49-9a8e-c2055c3e1607.jpeg)

**Comment by nank1ro** [comment] 2021-11-22 09:11
Hello, thank for your report.
This is a duplicate of [this issue](https://github.com/nank1ro/codigo-questions/issues/23).
Today I sent the version 2.0.4 in review, and I'm waiting for the approval. This new version fixes this problem.

**Comment by nank1ro** [comment] 2021-11-22 10:06
@all-contributors please add @zeykk for bug

**Comment by nank1ro** [comment] 2021-11-22 10:06
closing because the version 2.0.4 that fixes this problem is live in both the Play Store and the App Store.
If you encounter this bug again, consider opening a new issue.

**Closed as completed by nank1ro** 2021-11-22 10:06 UTC
Labels: bug
