### ISSUE TITLE
[Bug] exercise "it/c/arithmeticOperators/7.md" has an issue 

### ISSUE THREAD

**Issue by simolado** [nank1ro/codigo-questions#38] opened 2021-11-24 22:11 UTC
This exercise has an issue in fact I can’t press the button play when I’m done. Can someone help me?

**Comment by simolado** [comment] 2021-11-24 22:12
![9ED4D424-78CE-4E84-AB2C-D84AAA9DBCF5](https://user-images.githubusercontent.com/91845095/143319258-a14d95b1-9a7c-458e-8dc9-964d2112a0b5.png)

**Comment by nank1ro** [comment] 2021-11-25 09:39
Hi,

thank you for your report.
I have reproduced the bug reported, I'm trying to figure out what the problem is.
As soon as I have news I'll let you know.

**Comment by nank1ro** [comment] 2021-11-25 09:39
@all-contributors please add @simolado for bug

**Comment by nank1ro** [comment] 2021-11-25 19:53
I found a bug in the app, I'm releasing the version 2.0.5 that will fix this problem.

I will let you know when the app is live.

**Comment by nank1ro** [comment] 2021-11-26 12:40
Closing because the app is live, now you should be able to complete the exercise successfully

**Closed as completed by nank1ro** 2021-11-26 12:40 UTC
Labels: bug
